[package]
name = "borpr"
version = "0.1.0"
edition = "2024"



[dependencies]

eframe = "0.29.0"
egui = "0.29.0"


html5ever = "0.27.0"
markup5ever_rcdom = "0.3.0"

reqwest = "0.12.5"
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1.3"
cssparser = "0.31.2"